<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.mycompany.app</groupId>
  <artifactId>my-app</artifactId>
  <version>1.9-SNAPSHOT</version>

  <name>my-app</name>
  <url>https://com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>21</maven.compiler.release>
  </properties>

  <scm>
    <developerConnection>scp:git:ssh://git@github.com/tirerack/my-app.git</developerConnection>
    <url>https://github.com/tirerack/my-app</url>
    <tag>HEAD</tag>
  </scm>

  <distributionManagement>
    <repository>
      <id>jfrog-cloud</id>
      <name>tirerack-maven-releases</name>
      <url>https://tirerack.jfrog.io/artifactory/maven-release-local</url>
    </repository>
    <snapshotRepository>
      <id>jfrog-cloud</id>
      <name>tirerack-maven-snapshots</name>
      <url>https://tirerack.jfrog.io/artifactory/maven-snapshot-local</url>
    </snapshotRepository>
</distributionManagement>

<repositories>
  <repository>
    <id>maven-release</id>
    <name>maven-release</name>
    <url>https://tirerack.jfrog.io/artifactory/maven-release</url>
    <releases>
      <enabled>true</enabled>
      <updatePolicy>always</updatePolicy>
      <checksumPolicy>warn</checksumPolicy>
    </releases>
    <snapshots>
      <enabled>false</enabled>
    </snapshots>
  </repository>
  <repository>
    <id>maven-snapshot</id>
    <name>maven-snapshot</name>
    <url>https://tirerack.jfrog.io/artifactory/maven-snapshot</url>
    <releases>
      <enabled>false</enabled>
    </releases>
    <snapshots>
      <enabled>true</enabled>
      <updatePolicy>always</updatePolicy>
      <checksumPolicy>warn</checksumPolicy>
    </snapshots>
  </repository>
</repositories>

<pluginRepositories>
  <pluginRepository>
    <id>maven-release</id>
    <name>maven-release</name>
    <url>https://tirerack.jfrog.io/artifactory/maven-release</url>
    <snapshots>
      <enabled>false</enabled>
    </snapshots>
  </pluginRepository>
  <pluginRepository>
    <id>maven-snapshot</id>
    <name>maven-snapshot-local</name>
    <url>https://tirerack.jfrog.io/artifactory/maven-snapshot</url>
    <releases>
      <enabled>false</enabled>
    </releases>
  </pluginRepository>
</pluginRepositories>

  <dependencyManagement>
    <dependencies>
    <!--<dependency>
        <groupId>com.tirerack.microservices.commons</groupId>
        <artifactId>commons-dependencies-bom</artifactId>
        <version>0.0.3</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.tirerack.microservices.commons</groupId>
        <artifactId>commons-dev-toolkit</artifactId>
        <version>0.0.2</version>
        <scope>provided</scope>
    </dependency> -->
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>5.11.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <!--<dependency>
      <groupId>com.tirerack.microservices.commons</groupId>
      <artifactId>commons-dev-toolkit</artifactId>
    </dependency> -->
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- Optionally: parameterized tests support -->
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-params</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
      <plugins>
        <!-- clean lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#clean_Lifecycle -->
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.4.0</version>
        </plugin>
        <!-- default lifecycle, jar packaging: see https://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.3.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.13.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>3.3.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.4.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>3.1.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>3.1.2</version>
        </plugin>
        <!-- site lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#site_Lifecycle -->
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.12.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.6.1</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
